// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLThuGomRac_UNETI02_TI17A1HN.Data;

#nullable disable

namespace QLThuGomRac_UNETI02_TI17A1HN.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.ChiTietYeuCau", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaLoaiRac")
                        .HasColumnType("int");

                    b.Property<int>("MaYeuCau")
                        .HasColumnType("int");

                    b.Property<decimal>("SoLuongDuKien")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaLoaiRac");

                    b.HasIndex("MaYeuCau", "MaLoaiRac")
                        .IsUnique();

                    b.ToTable("ChiTietYeuCaus", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietYeuCau_SoLuong", "[SoLuongDuKien] > 0");
                        });
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.KhuVuc", b =>
                {
                    b.Property<int>("MaKhuVuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhuVuc"));

                    b.Property<string>("DiaChiMoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenKhuVuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaKhuVuc");

                    b.HasIndex("TenKhuVuc")
                        .IsUnique();

                    b.ToTable("KhuVucs");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.LoaiRac", b =>
                {
                    b.Property<int>("MaLoaiRac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoaiRac"));

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenLoaiRac")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaLoaiRac");

                    b.HasIndex("TenLoaiRac")
                        .IsUnique();

                    b.ToTable("LoaiRacs");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NguoiDan", b =>
                {
                    b.Property<int>("MaNguoiDan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDan"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int?>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNguoiDan");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("NguoiDans");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhanVien"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaNhanVien");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.PhanCongThuGom", b =>
                {
                    b.Property<int>("MaPhanCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanCong"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LyDoKhongThucHien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("MaYeuCau")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhanCong");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaYeuCau")
                        .IsUnique();

                    b.ToTable("PhanCongThuGoms");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoaiTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.YeuCauThuGom", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<string>("DiaChiThuGom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KhoaChongTrung")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("KhungGio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("MaKhuVuc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayMongMuonThuGom")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoaiLienHe")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("KhoaChongTrung")
                        .IsUnique()
                        .HasFilter("[TrangThai] <> 6 AND [TrangThai] <> 7");

                    b.HasIndex("MaKhuVuc");

                    b.HasIndex("MaNguoiDan", "TrangThai", "NgayDangKy");

                    b.ToTable("YeuCauThuGoms");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.ChiTietYeuCau", b =>
                {
                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.LoaiRac", "LoaiRac")
                        .WithMany()
                        .HasForeignKey("MaLoaiRac")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.YeuCauThuGom", "YeuCauThuGom")
                        .WithMany("ChiTietYeuCaus")
                        .HasForeignKey("MaYeuCau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiRac");

                    b.Navigation("YeuCauThuGom");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NguoiDan", b =>
                {
                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NguoiDan", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NhanVien", b =>
                {
                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.KhuVuc", "KhuVuc")
                        .WithMany()
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.TaiKhoan", "TaiKhoan")
                        .WithOne()
                        .HasForeignKey("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NhanVien", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuVuc");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.PhanCongThuGom", b =>
                {
                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.YeuCauThuGom", "YeuCauThuGom")
                        .WithOne()
                        .HasForeignKey("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.PhanCongThuGom", "MaYeuCau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("YeuCauThuGom");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.YeuCauThuGom", b =>
                {
                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.KhuVuc", "KhuVuc")
                        .WithMany()
                        .HasForeignKey("MaKhuVuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.NguoiDan", "NguoiDan")
                        .WithMany()
                        .HasForeignKey("MaNguoiDan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhuVuc");

                    b.Navigation("NguoiDan");
                });

            modelBuilder.Entity("QLThuGomRac_UNETI02_TI17A1HN.Models.Entities.YeuCauThuGom", b =>
                {
                    b.Navigation("ChiTietYeuCaus");
                });
#pragma warning restore 612, 618
        }
    }
}
